"""Agent tutor node — LangGraph node that routes after LLM-driven judging.

This node receives the output from ``agent_judge_node`` and decides
where to route next based on the verdict. The warm feedback and repair
suggestion have already been generated by the LLM in the judge node;
this node only handles the routing decision.

**Graph topology (agent mode)**:

    agent_judge_node → agent_tutor_node [HERE]
         │                              │
         │  AC?  → done (goto planner)  │
         │  WA?  → wait_for_submit_node ←── user submits again
         ▼                              │
    (back to agent_judge_node, cycle+1)

**Routing logic**:

    - ``last_verdict == "AC"`` → status = "done", goto = "planner_node"
      (session complete, user can start a new topic)

    - ``last_verdict != "AC"`` → status = "awaiting_submit"
      goto = "wait_for_submit_node" (loop back for code fix + resubmit)

    The warm feedback and repair suggestion are already stored in
    ``warm_feedback`` and ``repair_suggestion`` state fields by
    ``agent_judge_node``, so this node just passes them through.
"""

from __future__ import annotations

import logging

from langgraph.types import Command

from code_tutor_agent.schemas.state import SessionState

logger = logging.getLogger(__name__)

# ── AC 完成消息池（每次随机选一个） ──
_AC_MESSAGES = [
    "🎉 全部通过！你的代码逻辑正确。",
    "✅ AC！要不要试试不同解法优化一下？",
    "✅ 完美通过！下一题继续加油 💪",
    "🎊 AC 了！可以去看看参考代码对比一下思路。",
]


def agent_tutor_node(state: SessionState) -> Command:
    """Route after agent judging based on the verdict.

    Args:
        state: Session state with ``last_verdict``, ``warm_feedback``,
               ``repair_suggestion``, ``judge_cycle`` set by
               ``agent_judge_node``.

    Returns:
        Command routing to ``planner_node`` (AC) or
        ``wait_for_submit_node`` (WA/RE/TLE).
    """
    verdict = state.last_verdict or ""
    cycle = state.judge_cycle
    logger.info("▶ agent_tutor_node() — verdict=%s cycle=%d", verdict, cycle)

    # ── AC: 全部通过 → 完成 ──
    if verdict == "AC":
        logger.info("AC on cycle %d — session done", cycle)
        return Command(
            update={
                "status": "done",
            },
            goto="planner_node",
        )

    # ── 未通过 → 循环等待用户修改 ──
    logger.info("Not AC (verdict=%s) — routing back to wait_for_submit (cycle %d)", verdict, cycle)
    return Command(
        update={
            "status": "awaiting_submit",
        },
        goto="wait_for_submit_node",
    )